[backend]
# database   binary database faster queries 1 gpg and python (easier ha)
											# leave set
backend = "database"


# default for asymmetrical gpg auth for STATPST
                                                        # asks for paraphrase and caches for 15 minutes
                                                        # leave default
email = "john.doe@email.com"
name = "John e"


[logs]

# default 200mb to disable compression on .gpg size. disabling compression can increase speed by up to 50% when at large sizes
compLVL = 200


[search]

# Directories to exclude from the searches. ie home/guest/somefolder
# default directories that are left "/bin", "/etc", "/home", "/lib", "/lib64", "/opt", "/root", "/sbin", "/tmp", "/usr",  "/var"
EXCLDIRS = ["dev", "mnt", "proc", "run", "srv", "sys"]	


# handle switching automatically? mMODE also known as turbo mode.  
mMODE = "mc"		#  mc   will run the search in parallel or multiple cores if over a certain number of file result threshhold. otherwise runs serially. mc is default
							# default   if set to default you have a hard drive run the searches serially

# run inotifywait for one hour to look for new files where ctime > mtime in /changes. this is for downloads or copies with preserved metadata pacman slackpkg ect.
# It just dynamically bypasses a section of the script if tout result is already made. It is also inserted into the cache ctimecache.gpg.
xRC = false             # false - default. if false the files will still show up
							    # true - With this setting can bypass 1 of 2 search loops and reduce process overhead as the search is already there effectively increasing the overall speed

						# How many old searches to save and rnt.xzm. These can be grabbed by `recentchanges search` and `recentchanges`
                        # for comparisons in diff file
archivesrh = 5


# SRC  `recentchanges SRC`. if an xzmname isnt provided a default one Application$$.xzm is used.
# if distro not porteus the SRC tag is bypassed
autooutput = false
xzmname = ""

                   # default gzip. uses gzip compression level balanced. This is for recentchanges .xzm and SRC tag
                                           # xz        best compression
                                           # zstd     faster bootup
                                            # lzo      faster bootup
cmode = "gzip"
# end SRC

# Note: set mMODE to default for debug as fsearch or hanlyparralle are parallell and can confuse the log
					# ERROR log only critical errors
					# DEBUG show all in log for diagnostics
logLEVEL = "ERROR"

[analytics]

# provides more feedback
                            # total search time ect
                            # we dont want too much output on the terminal just a slight bit more
                            # others stats
ANALYTICSECT = true


# include find output in terminal as well ie scrolling terminal look
FEEDBACK = true


[display]

#launch text editor?
# if using somethingelse specifying dspPATH is required
						# xed  default 
							# "false" or false
							# ""
							# featherpad
							# xed
dspEDITOR = "xed"


# specify absolute directory as a fallback incase cant find it in Path. xed is fine but needed for other editors. recommended
# if the value "" is used the app will check registry for dspEDITOR to see if its installed. featherpad and xed
# else needs dspPATH specifcally for other editor or if xed featherpad are installed somewhere not in path
													# ""
													# "/usr/bin/xed"
													# "/usr/bin/somebinary"
dspPATH = ""


[diagnostics]
# compare file checksums for slight changes
										# slower useful if you want to check deeper level of stats
checkSUM = true
 # Include stealth changes in diff file    a file was changed but has the same checksum and filesize subtle edit  ie cache items or string was changed
									# also check for hash collisions
cdiag = true

# supress cache warnings on terminal from known browsers? Mozilla... ect list top of rntfuncions. see /usr/local/save-changesnew/pyfunctions.py
supbrw = true

# ..      all cdiag output to terminal except critical events
supress = false

# scan for accurate hardlinks in db. alternatively use Set hardlinks button
updatehlinks = true

# Diagnostics. Create file doctrine. Runs post search operation that can only be done at this time as search is relevant
                                    # more overhead so recommend off unless one off. output /Downloads
                                    #
                                    # if it is run again and a file is still there it will not run the POSTOP and the script will set POSTOP to false to itself
POSTOP = false

# take initial hash of base modules 001-core..
proteusSHIELD = false


[paths]
# file label prefix for searches output txt file			# default rntfiles
MODULENAME = "rntfiles" 

